package ar.edu.itba.paw.model;

public enum Categories {
    LIMPIEZA,
    PELUQUERIA,
    BELLEZA,
    GASASISTA,
    GASISTA,
    PLOMERO,
    ELECTRICISTA,
    JARDINERIA,
    MUDANZAS,
    FONTANERO,
    CARPINTERIA,
    REPARACION_ELECTRODOMESTICOS,
    PINTOR,
    CERRAJERO,
    SERVICIO_INFORMATICO,
    FOTOGRAFIA,
    TRANSPORTE,
    CUIDADO_DE_NIÑOS,
    CUIDADO_DE_ANCIANOS,
    ENTRETENIMIENTO,
    CONSULTORIA_FINANCIERA,
    DISEÑO_GRAFICO,
    ENTRENADOR_PERSONAL

}
